{{- if .EnablePostgresMetrics }}
apiVersion: v1
data:
  acm-global-postgres-tables.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "datasource",
              "uid": "grafana"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "description": "This dashboard works with postgres_exporter for prometheus",
      "editable": true,
      "fiscalYearStartMonth": 0,
      "gnetId": 9628,
      "graphTooltip": 0,
      "id": 18,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "grafana-postgresql-datasource",
            "uid": "P244538DD76A4C61D"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "filterable": true,
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unitScale": true
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Index OID"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 91
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Table Name"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 236
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 9,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 79,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "enablePagination": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true,
            "sortBy": []
          },
          "pluginVersion": "10.3.3",
          "targets": [
            {
              "datasource": {
                "type": "grafana-postgresql-datasource",
                "uid": "P244538DD76A4C61D"
              },
              "editorMode": "code",
              "format": "table",
              "rawQuery": true,
              "rawSql": "SELECT \nschemaname, relname, seq_scan, idx_scan, n_tup_ins, n_tup_upd, n_tup_del, n_live_tup, n_dead_tup,last_autovacuum,autovacuum_count\nFROM pg_stat_all_tables\nWHERE schemaname IN ( 'status', 'event', 'history', 'local_spec', 'local_status' )\nORDER BY seq_scan desc\n",
              "refId": "A",
              "sql": {
                "columns": [
                  {
                    "parameters": [],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              }
            }
          ],
          "title": "All Tables",
          "transformations": [
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "relid": true
                },
                "includeByName": {},
                "indexByName": {},
                "renameByName": {
                  "autovacuum_count": "Auto Vacuum Count",
                  "idx_scan": "Number Of Index Scans",
                  "idx_tup_fetch": "Number Of index Fetch",
                  "idx_tup_read": "Number Of Index Read",
                  "indexrelid": "Index OID",
                  "indexrelname": "Index Name",
                  "last_autovacuum": "Last Auto Vacuum",
                  "n_dead_tup": "Number Of Dead Rows",
                  "n_live_tup": "Number Of Live Rows",
                  "n_tup_del": "Delete Rows",
                  "n_tup_ins": "Insert Rows",
                  "n_tup_upd": "Update Rows",
                  "relname": "Table Name",
                  "schemaname": "Schema Name",
                  "seq_scan": "Number Of Sequential Scans",
                  "seq_tup_read": "Number Of Read"
                }
              }
            }
          ],
          "type": "table"
        },
        {
          "datasource": {
            "type": "grafana-postgresql-datasource",
            "uid": "P244538DD76A4C61D"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "filterable": true,
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unitScale": true
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Schema"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 207
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 9
          },
          "id": 84,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true,
            "sortBy": []
          },
          "pluginVersion": "10.3.3",
          "targets": [
            {
              "datasource": {
                "type": "grafana-postgresql-datasource",
                "uid": "P244538DD76A4C61D"
              },
              "editorMode": "code",
              "format": "table",
              "rawQuery": true,
              "rawSql": "select schemaname, relname, pg_size_pretty(pg_relation_size(relid)) from pg_stat_user_tables  order by pg_relation_size(relid) desc;",
              "refId": "A",
              "sql": {
                "columns": [
                  {
                    "parameters": [],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              }
            }
          ],
          "title": "Table Size",
          "transformations": [
            {
              "id": "organize",
              "options": {
                "excludeByName": {},
                "includeByName": {},
                "indexByName": {},
                "renameByName": {
                  "pg_size_pretty": "Size",
                  "relname": "Table",
                  "schemaname": "Schema"
                }
              }
            }
          ],
          "type": "table"
        },
        {
          "datasource": {
            "type": "grafana-postgresql-datasource",
            "uid": "P244538DD76A4C61D"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "none",
              "unitScale": false
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Index Usage Percent"
                },
                "properties": [
                  {
                    "id": "unit",
                    "value": "percent"
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 9
          },
          "id": 82,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true,
            "sortBy": [
              {
                "desc": true,
                "displayName": "rows_in_table"
              }
            ]
          },
          "pluginVersion": "10.3.3",
          "targets": [
            {
              "datasource": {
                "type": "grafana-postgresql-datasource",
                "uid": "P244538DD76A4C61D"
              },
              "editorMode": "code",
              "format": "table",
              "rawQuery": true,
              "rawSql": "SELECT relname, 100 * idx_scan / (seq_scan + idx_scan) percent_of_times_index_used, n_live_tup rows_in_table\n    FROM pg_stat_user_tables ORDER BY n_live_tup DESC;",
              "refId": "A",
              "sql": {
                "columns": [
                  {
                    "parameters": [],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              }
            }
          ],
          "title": "Index Usage By Table",
          "transformations": [
            {
              "id": "organize",
              "options": {
                "excludeByName": {},
                "includeByName": {},
                "indexByName": {
                  "percent_of_times_index_used": 2,
                  "relname": 0,
                  "rows_in_table": 1
                },
                "renameByName": {
                  "percent_of_times_index_used": "Index Usage Percent",
                  "relname": "Table Name",
                  "rows_in_table": "Rows In Table"
                }
              }
            }
          ],
          "type": "table"
        },
        {
          "datasource": {
            "type": "grafana-postgresql-datasource",
            "uid": "P244538DD76A4C61D"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "filterable": true,
                "inspect": false
              },
              "fieldMinMax": false,
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "none",
              "unitScale": false
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Index Scan Percentage"
                },
                "properties": [
                  {
                    "id": "unit",
                    "value": "percent"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Index Name"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 550
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 17
          },
          "id": 80,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "enablePagination": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true,
            "sortBy": [
              {
                "desc": true,
                "displayName": "Index Scans"
              }
            ]
          },
          "pluginVersion": "10.3.3",
          "targets": [
            {
              "datasource": {
                "type": "grafana-postgresql-datasource",
                "uid": "P244538DD76A4C61D"
              },
              "editorMode": "code",
              "format": "table",
              "rawQuery": true,
              "rawSql": "\nSELECT t.relname AS table_name, i.indexrelname AS index_name, t.seq_scan AS table_scans,\n    i.idx_scan AS index_scans, round(i.idx_scan::numeric / (i.idx_scan + t.seq_scan) * 100, 2) AS index_scan_percentage\n    FROM pg_stat_user_tables t JOIN pg_stat_user_indexes i ON t.relid = i.relid\n    WHERE  t.seq_scan + i.idx_scan > 0\n    ORDER BY index_scan_percentage DESC;",
              "refId": "A",
              "sql": {
                "columns": [
                  {
                    "parameters": [],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              }
            }
          ],
          "title": "Index Usage",
          "transformations": [
            {
              "id": "organize",
              "options": {
                "excludeByName": {},
                "includeByName": {},
                "indexByName": {},
                "renameByName": {
                  "index_name": "Index Name",
                  "index_scan_percentage": "Index Scan Percentage",
                  "index_scans": "Index Scans",
                  "table_name": "Table Name",
                  "table_scans": "Table Scans"
                }
              }
            }
          ],
          "type": "table"
        }
      ],
      "refresh": "",
      "schemaVersion": 39,
      "tags": [
        "postgres",
        "db",
        "table",
        "index"
      ],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "Prometheus",
              "value": "PBFA97CFB590B2093"
            },
            "hide": 2,
            "includeAll": false,
            "label": "datasource",
            "multi": false,
            "name": "DS_PROMETHEUS",
            "options": [],
            "query": "prometheus",
            "queryValue": "",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "type": "datasource"
          }
        ]
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {
        "hidden": true,
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ]
      },
      "timezone": "",
      "title": "PostgreSQL Tables And Indexes",
      "uid": "000000002",
      "version": 2,
      "weekStart": ""
    }
kind: ConfigMap
metadata:
  name: grafana-dashboard-acm-global-postgres-tables
  namespace: {{ .Namespace }}
{{- end }}
