apiVersion: v1
data:
  acm-global-whats-changed.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "iteration": 1685628888333,
      "links": [
        {
          "asDropdown": false,
          "icon": "dashboard",
          "includeVars": false,
          "keepTime": false,
          "tags": [],
          "targetBlank": true,
          "title": "Offending Clusters",
          "tooltip": "",
          "type": "link",
          "url": "d/0e0ddb7f16b946f99d96a483a4a3f95f/global-hub-offending-clusters?orgId=1"
        },
        {
          "asDropdown": false,
          "icon": "dashboard",
          "includeVars": false,
          "keepTime": false,
          "tags": [],
          "targetBlank": true,
          "title": "Offending Policies",
          "tooltip": "",
          "type": "link",
          "url": "d/b67e0727891f4121ae2dde09671520ae/global-hub-offending-policies?orgId=1"
        }
      ],
      "panels": [
        {
          "datasource": "${datasource}",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "fillOpacity": 70,
                "lineWidth": 0
              },
              "mappings": [],
              "noValue": "-",
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "red",
                    "value": null
                  },
                  {
                    "color": "dark-yellow",
                    "value": 0.5
                  },
                  {
                    "color": "green",
                    "value": 0.9
                  }
                ]
              },
              "unit": "percentunit"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 11,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 12,
          "options": {
            "alignValue": "left",
            "legend": {
              "displayMode": "list",
              "placement": "bottom"
            },
            "mergeValues": true,
            "rowHeight": 0.9,
            "showValue": "auto",
            "tooltip": {
              "mode": "single"
            }
          },
          "pluginVersion": "8.5.20",
          "targets": [
            {
              "format": "time_series",
              "group": [],
              "metricColumn": "none",
              "rawQuery": true,
              "rawSql": "WITH data as (\n  SELECT \n    $__timeGroupAlias(ch.compliance_date, $__interval),\n    mc.cluster_name AS \"metric\",\n    COUNT(CASE WHEN ch.compliance = 'compliant' THEN 1 END) AS \"compliant\",\n    COUNT(CASE WHEN ch.compliance = 'non_compliant' THEN 1 END) AS \"non_compliant\",\n    COUNT(CASE WHEN ch.compliance = 'unknown' THEN 1 END) AS \"unknown\"\n  FROM\n    history.local_compliance ch\n  INNER JOIN\n    local_spec.policies p ON ch.policy_id = p.policy_id\n  INNER JOIN\n    status.managed_clusters mc ON ch.cluster_id = mc.cluster_id\n  WHERE\n    $__timeFilter(ch.compliance_date)\n  AND\n    mc.cluster_name IN ($cluster)\n  AND\n    policy_name IN ($policy)\n  GROUP BY (ch.compliance_date, mc.cluster_name)\n  ORDER BY (time)\n)\nSELECT\n  time,\n  metric,\n  compliant::float / NULLIF((compliant::float + non_compliant), 0) as \"value\"\nFROM\n  data",
              "refId": "A",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "column"
                  }
                ]
              ],
              "timeColumn": "time",
              "where": [
                {
                  "name": "$__timeFilter",
                  "params": [],
                  "type": "macro"
                }
              ]
            }
          ],
          "timeFrom": null,
          "title": "Policy State Timeline",
          "type": "state-timeline"
        },
        {
          "datasource": null,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 11
          },
          "id": 6,
          "title": "Events",
          "type": "row"
        },
        {
          "datasource": "${datasource}",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "displayMode": "auto",
                "filterable": true
              },
              "mappings": [
                {
                  "options": {
                    "compliant": {
                      "color": "green",
                      "index": 0,
                      "text": "true"
                    },
                    "non_compliant": {
                      "color": "red",
                      "index": 1,
                      "text": "false"
                    }
                  },
                  "type": "value"
                }
              ],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "dark-yellow",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "compliance"
                },
                "properties": [
                  {
                    "id": "custom.displayMode",
                    "value": "color-background"
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 9,
            "w": 24,
            "x": 0,
            "y": 12
          },
          "id": 4,
          "interval": null,
          "options": {
            "showHeader": true,
            "sortBy": [
              {
                "desc": true,
                "displayName": "date_id"
              }
            ]
          },
          "pluginVersion": "8.5.20",
          "targets": [
            {
              "format": "table",
              "group": [],
              "metricColumn": "none",
              "rawQuery": true,
              "rawSql": "SELECT\n  $__timeGroupAlias(lp.created_at, $__interval),\n  p.policy_name,\n  mc.cluster_name,\n  lp.message,\n  lp.reason,\n  lp.compliance\nFROM\n  event.local_policies lp\nINNER JOIN\n  local_spec.policies p ON lp.policy_id = p.policy_id\nINNER JOIN\n  status.managed_clusters mc ON lp.cluster_id = mc.cluster_id\nWHERE\n  $__timeFilter(lp.created_at)\nAND\n  policy_name IN ($policy)\nAND\n  cluster_name IN ($cluster)\nORDER BY (lp.created_at) DESC",
              "refId": "A",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "column"
                  }
                ]
              ],
              "timeColumn": "time",
              "where": [
                {
                  "name": "$__timeFilter",
                  "params": [],
                  "type": "macro"
                }
              ]
            }
          ],
          "timeFrom": null,
          "title": "Policy Events",
          "transformations": [
            {
              "id": "organize",
              "options": {
                "excludeByName": {},
                "indexByName": {
                  "cluster_name": 2,
                  "message": 3,
                  "policy_name": 1,
                  "reason": 4,
                  "source": 5,
                  "time": 0
                },
                "renameByName": {
                  "cluster_id": "ClusterID",
                  "cluster_name": "Cluster",
                  "compliance": "Compliance",
                  "message": "Message",
                  "policy_name": "Policy",
                  "reason": "Reason",
                  "source": "Source",
                  "time": "Time"
                }
              }
            }
          ],
          "type": "table"
        }
      ],
      "refresh": false,
      "schemaVersion": 30,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "Global-Hub-DataSource",
              "value": "Global-Hub-DataSource"
            },
            "description": null,
            "error": null,
            "hide": 2,
            "includeAll": false,
            "label": "Datasource",
            "multi": false,
            "name": "datasource",
            "options": [],
            "query": "postgres",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "type": "datasource"
          },
          {
            "allValue": null,
            "current": {
              "selected": false,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": "${datasource}",
            "definition": "SELECT\n  cluster_name\nFROM\n  status.managed_clusters mc\nINNER JOIN\n  history.local_compliance ch ON mc.cluster_id = ch.cluster_id",
            "description": null,
            "error": null,
            "hide": 0,
            "includeAll": true,
            "label": "Cluster",
            "multi": true,
            "name": "cluster",
            "options": [],
            "query": "SELECT\n  cluster_name\nFROM\n  status.managed_clusters mc\nINNER JOIN\n  history.local_compliance ch ON mc.cluster_id = ch.cluster_id",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 5,
            "type": "query"
          },
          {
            "allValue": null,
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": "${datasource}",
            "definition": "SELECT\n  policy_name\nFROM\n  local_spec.policies p\nINNER JOIN\n  history.local_compliance ch ON p.policy_id = ch.id\nINNER JOIN\n  status.managed_clusters mc ON ch.cluster_id = mc.cluster_id\nWHERE\n  cluster_name IN ($cluster)",
            "description": null,
            "error": null,
            "hide": 0,
            "includeAll": true,
            "label": "Policy",
            "multi": true,
            "name": "policy",
            "options": [],
            "query": "SELECT\n  policy_name\nFROM\n  local_spec.policies p\nINNER JOIN\n  history.local_compliance ch ON p.policy_id = ch.id\nINNER JOIN\n  status.managed_clusters mc ON ch.cluster_id = mc.cluster_id\nWHERE\n  cluster_name IN ($cluster)",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 5,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-7d",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "utc",
      "title": "Global Hub - What's Changed",
      "uid": "5a3a577af7894943aa6e7ca8408502fa",
      "version": 1
    }
kind: ConfigMap
metadata:
  name: grafana-dashboard-acm-global-whats-changed
  namespace: {{.Namespace}}
