apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: default
  namespace: {{.Namespace}}
spec:
  numberOfClusters: 1
  prioritizerPolicy:
    configurations:
    - scoreCoordinate:
        builtIn: ResourceAllocatableMemory
        type: BuiltIn
      weight: 1
    - scoreCoordinate:
        builtIn: Steady
        type: BuiltIn
      weight: 3
    mode: Exact
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: local-cluster
          operator: NotIn
          values:
          - "true"