apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: inventory-api
  name: inventory-api
  namespace: {{.Namespace}}
spec:
  port:
    targetPort: http-server
  tls:
    insecureEdgeTerminationPolicy: None
    termination: edge
  to:
    kind: Service
    name: inventory-api
    weight: 100
  wildcardPolicy: None
