apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: {{.KafkaCluster}}
  namespace: {{.Namespace}}
spec:
  replicas: {{.TopicReplicas}}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{.StorageSize}}
        deleteClaim: false
        kraftMetadata: shared
        {{ if .StorageClass }}
        class: {{.StorageClass}}
        {{ end }}
