apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hoh
  namespace: hoh-postgres
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1
  postgresVersion: 13
  users:
    - name: "postgres"
      databases: ["hoh"]
    - name: "hoh-process-user"
      databases: ["hoh"]
    - name: "transport-bridge-user"
      databases: ["hoh"]
  instances:
    - name: pgha1
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: hoh
                    postgres-operator.crunchydata.com/instance-set: pgha1
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-3
      replicas: 1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: hoh
                    postgres-operator.crunchydata.com/role: pgbouncer
---
# The configMap is used to set/unset HA configuration
# To set HA:
#   1. Use DisableAutofail: "false" or omit it
#   2. Define at least 2 replicas in "instances" and "proxy" sections of the above PostgresCluster CR
# To unset HA:
#   1. Use DisableAutofail: "true"
#   2. Define 1 replica in "instances" and "proxy" sections of the above PostgresCluster CR
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgo-config
  namespace: hoh-postgres
data:
  DisableAutofail: "true"
