apiVersion: v1
kind: ConfigMap
metadata:
  name: multicluster-global-hub-postgres-init
  namespace: {{.Namespace}}
data:
  postgresql-start.sh: |
    psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'inventory'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE inventory"
    psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'hoh'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE hoh"
    psql -U postgres -tc "SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = '{{.PostgresReadonlyUsername}}'" | grep -q 1 || psql -U postgres -c "CREATE ROLE \"{{.PostgresReadonlyUsername}}\" LOGIN PASSWORD '{{.PostgresReadonlyUserPassword}}'"
    psql -U postgres -c "ALTER ROLE \"{{.PostgresReadonlyUsername}}\" WITH PASSWORD '{{.PostgresReadonlyUserPassword}}'"     
