apiVersion: v1
kind: Secret
metadata:
  name: multicluster-global-hub-postgres
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-postgres
  annotations:
    skip-creation-if-exist: "true"
type: Opaque
stringData:
  database-admin-password: "{{.PostgresAdminUserPassword}}"
  database-readonly-user: "{{.PostgresReadonlyUsername}}"
  database-readonly-password: "{{.PostgresReadonlyUserPassword}}"
  "ca.crt": "{{.PostgresCACert}}"
