apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: spec
  namespace: multicluster-global-hub-kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: status
  namespace: multicluster-global-hub-kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: event
  namespace: multicluster-global-hub-kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
