apiVersion: operator.open-cluster-management.io/v1alpha2
kind: MulticlusterGlobalHub
metadata:
  # annotations:
    # mgh-pause: "true"
    # mgh-image-repository: quay.io/<quay_io_repo>
    # mgh-image-overrides-cm: mgh-images-config
    # mgh-hub-ACM-snapshot: 2.5.0-SNAPSHOT-2022-05-13-20-43-27
    # mgh-hub-MCE-snapshot: 2.0.0-BACKPLANE-2022-05-13-17-52-12
    # mgh-kafka-bootstrap-server: kafka-brokers-cluster-kafka-external-bootstrap-kafka.apps.testing.example.com
  name: multiclusterglobalhub
spec:
  dataLayer:
    type: largeScale
    largeScale:
      kafka:
        name: transport-secret
        transportFormat: cloudEvents
      postgres:
        name: storage-secret
