name: Deploy Global Hub Without ACM

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.25'
  GO_REQUIRED_MIN_VERSION: ''

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check initial disk usage
        run: df -h /
      - name: Free disk space (optional cleanup)
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache
          docker system prune -af
          df -h /
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.15.0
      - name: SET E2E
        run: |
          make kessel-e2e-setup
      - name: RUN E2E
        run: |
          make kessel-e2e-run
  
